FROM python:3.14.0-slim

WORKDIR /app

COPY . /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=app1.py

ENV FLASK_RUN_HOST=0.0.0.0

CMD ["flask","run","--host=0.0.0.0","--port=5000"]
